version: '3'

services:
  cloud-weather-postgress:
    image: debezium/postgres:13-alpine
    environment:
      POSTGRES_USER: cloud_weather_dev
      POSTGRES_PASSWORD: cloud_weather_dev
      POSTGRES_DATABASE: cloud_weather_dev
    volumes:
      - postgres-data:/data/db
    ports:
      - "5432:5432"

volumes:
  postgres-data:
